In [1]:
import os 
import pandas as pd
import numpy as np

os.chdir("../")
os.getcwd()

'c:\\Users\\leoco\\Documents\\cours\\M2_MOSEF\\time_series_deep_learning\\Store_Sales_Time_Series_Forecasting'

In [2]:
from src.create_dataset import create_dataset, optimize_memory

In [3]:
main_df = pd.read_csv('data/main_df.csv', parse_dates=['date'])
stores_df = pd.read_csv('data/stores.csv')
oil_df = pd.read_csv('data/oil.csv', parse_dates=['date'])
holidays_df = pd.read_csv('data/holidays_events.csv', parse_dates=['date'])

In [4]:
main_df.head()

   id       date  store_nbr      family  sales  onpromotion
0   0 2013-01-01          1  AUTOMOTIVE    0.0            0
1   1 2013-01-01          1   BABY CARE    0.0            0
2   2 2013-01-01          1      BEAUTY    0.0            0
3   3 2013-01-01          1   BEVERAGES    0.0            0
4   4 2013-01-01          1       BOOKS    0.0            0

In [5]:
stores_df.head()

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [6]:
oil_df.head()

        date  dcoilwtico
0 2013-01-01         NaN
1 2013-01-02       93.14
2 2013-01-03       92.97
3 2013-01-04       93.12
4 2013-01-07       93.20

In [7]:
holidays_df.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [8]:
sales_df = create_dataset(main_df, stores_df, oil_df, holidays_df)

In [9]:
sales_df = optimize_memory(sales_df)

Mémoire initiale: 1247.78 MB
Mémoire finale: 472.38 MB
Réduction de: 62.1%

In [10]:
sales_df.head()

,id,date,store_nbr,family,sales,onpromotion,city,state,store_type,cluster,...,rolling_std_7,store_family_velocity,target_enc_store_family,oil_trend_30,promo_ratio_vs_avg,promo_during_payday,family_store_nb,family_state,family_onpromotion,is_family_unactive
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,...,NaN,NaN,0.000000,0.00,0.0,0,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0,0
1782,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,Quito,Pichincha,D,13,...,NaN,0.000000,0.000000,0.00,0.0,0,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0,0
3564,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,...,NaN,1.000000,1.000000,-0.17,0.0,0,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0,0
5346,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,...,NaN,1.666667,1.666667,-0.02,0.0,0,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0,0
7128,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,Quito,Pichincha,D,13,...,NaN,2.000000,2.000000,-0.02,0.0,0,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0,0

In [11]:
sales_df.isnull().sum()

id                              0
date                            0
store_nbr                       0
family                          0
sales                           0
onpromotion                     0
city                            0
state                           0
store_type                      0
cluster                         0
dcoilwtico                      0
holiday_type                    0
is_holiday_local                0
is_holiday_regional             0
is_holiday_national             0
is_store_closed                 0
day_of_week                     0
month                           0
year                            0
time_idx                        0
is_weekend                      0
is_payday                       0
month_sin                       0
month_cos                       0
day_sin                         0
day_cos                         0
is_earthquake_impact            0
days_to_christmas               0
sales_lag_1                  1782
sales_lag_2                  3564
sales_lag_3                  5346
sales_lag_4                  7128
sales_lag_5                  8910
sales_lag_6                 10692
sales_lag_7                 12474
sales_lag_14                24948
sales_lag_21                37422
sales_lag_28                49896
sales_lag_56                99792
sales_lag_364              648648
rolling_mean_7              12474
rolling_mean_28             49896
rolling_mean_56             99792
log_sales                       0
diff_sales                   3564
rolling_std_7               12474
store_family_velocity           1
target_enc_store_family         0
oil_trend_30                    0
promo_ratio_vs_avg              0
promo_during_payday             0
family_store_nb                 0
family_state                    0
family_onpromotion              0
is_family_unactive              0
dtype: int64

In [12]:
sales_df.dtypes

id                                  int32
date                       datetime64[ns]
store_nbr                            int8
family                           category
sales                             float32
onpromotion                         int16
city                             category
state                            category
store_type                       category
cluster                              int8
dcoilwtico                        float32
holiday_type                     category
is_holiday_local                     int8
is_holiday_regional                  int8
is_holiday_national                  int8
is_store_closed                      int8
day_of_week                          int8
month                                int8
year                                int16
time_idx                            int16
is_weekend                           int8
is_payday                            int8
month_sin                         float32
month_cos                         float32
day_sin                           float32
day_cos                           float32
is_earthquake_impact                 int8
days_to_christmas                   int16
sales_lag_1                       float32
sales_lag_2                       float32
sales_lag_3                       float32
sales_lag_4                       float32
sales_lag_5                       float32
sales_lag_6                       float32
sales_lag_7                       float32
sales_lag_14                      float32
sales_lag_21                      float32
sales_lag_28                      float32
sales_lag_56                      float32
sales_lag_364                     float32
rolling_mean_7                    float32
rolling_mean_28                   float32
rolling_mean_56                   float32
log_sales                         float32
diff_sales                        float32
rolling_std_7                     float32
store_family_velocity             float32
target_enc_store_family           float32
oil_trend_30                      float32
promo_ratio_vs_avg                float32
promo_during_payday                 int16
family_store_nb                  category
family_state                     category
family_onpromotion               category
is_family_unactive                   int8
dtype: object

In [13]:
sales_df.select_dtypes(include="category")

,family,city,state,store_type,holiday_type,family_store_nb,family_state,family_onpromotion
0,AUTOMOTIVE,Quito,Pichincha,D,Holiday,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0
1782,AUTOMOTIVE,Quito,Pichincha,D,Work Day,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0
3564,AUTOMOTIVE,Quito,Pichincha,D,Work Day,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0
5346,AUTOMOTIVE,Quito,Pichincha,D,Work Day,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0
7128,AUTOMOTIVE,Quito,Pichincha,D,Work Day,AUTOMOTIVE_1,AUTOMOTIVE_Pichincha,AUTOMOTIVE_0
...,...,...,...,...,...,...,...,...
2993627,SEAFOOD,El Carmen,Manabi,C,Transfer,SEAFOOD_54,SEAFOOD_Manabi,SEAFOOD_0
2995409,SEAFOOD,El Carmen,Manabi,C,Work Day,SEAFOOD_54,SEAFOOD_Manabi,SEAFOOD_1
2997191,SEAFOOD,El Carmen,Manabi,C,Work Day,SEAFOOD_54,SEAFOOD_Manabi,SEAFOOD_0
2998973,SEAFOOD,El Carmen,Manabi,C,Work Day,SEAFOOD_54,SEAFOOD_Manabi,SEAFOOD_0
3000755,SEAFOOD,El Carmen,Manabi,C,Holiday,SEAFOOD_54,SEAFOOD_Manabi,SEAFOOD_0

In [14]:
sales_df.to_parquet('data/sales_data.parquet')