In [1]:
import os 
import pandas as pd
import numpy as np

os.chdir("../")
os.getcwd()

'c:\\Users\\leoco\\Documents\\cours\\M2_MOSEF\\time_series_deep_learning\\Store_Sales_Time_Series_Forecasting'

In [2]:
from src.create_dataset import create_dataset

In [3]:
main_df = pd.read_csv('data/main_df.csv', parse_dates=['date'])
stores_df = pd.read_csv('data/stores.csv')
oil_df = pd.read_csv('data/oil.csv', parse_dates=['date'])
holidays_df = pd.read_csv('data/holidays_events.csv', parse_dates=['date'])

In [4]:
main_df.head()

   id       date  store_nbr      family  sales  onpromotion
0   0 2013-01-01          1  AUTOMOTIVE    0.0            0
1   1 2013-01-01          1   BABY CARE    0.0            0
2   2 2013-01-01          1      BEAUTY    0.0            0
3   3 2013-01-01          1   BEVERAGES    0.0            0
4   4 2013-01-01          1       BOOKS    0.0            0

In [5]:
stores_df.head()

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [6]:
oil_df.head()

        date  dcoilwtico
0 2013-01-01         NaN
1 2013-01-02       93.14
2 2013-01-03       92.97
3 2013-01-04       93.12
4 2013-01-07       93.20

In [7]:
holidays_df.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [8]:
sales_df = create_dataset(main_df, stores_df, oil_df, holidays_df)

In [9]:
sales_df

,id,date,store_nbr,family,sales,onpromotion,city,state,store_type,cluster,...,month_cos,day_sin,day_cos,is_payday,is_earthquake_impact,days_to_christmas,promo_ratio_vs_avg,store_family_velocity,sales_lag_7,rolling_mean_7
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,...,0.866025,0.781831,0.623490,0,0,358,0.000000,NaN,NaN,NaN
1782,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,Quito,Pichincha,D,13,...,0.866025,0.974928,-0.222521,0,0,357,0.000000,0.000000,NaN,NaN
3564,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,...,0.866025,0.433884,-0.900969,0,0,356,0.000000,1.000000,NaN,NaN
5346,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,...,0.866025,-0.433884,-0.900969,0,0,355,0.000000,1.666667,NaN,NaN
7128,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,Quito,Pichincha,D,13,...,0.866025,-0.974928,-0.222521,0,0,354,0.000000,2.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993627,2993627,2017-08-11,54,SEAFOOD,0.0,0,El Carmen,Manabi,C,3,...,-0.500000,-0.433884,-0.900969,0,0,136,0.000000,2.966667,0.0,3.000000
2995409,2995409,2017-08-12,54,SEAFOOD,1.0,1,El Carmen,Manabi,C,3,...,-0.500000,-0.974928,-0.222521,0,0,135,0.901017,2.933333,3.0,3.000000
2997191,2997191,2017-08-13,54,SEAFOOD,2.0,0,El Carmen,Manabi,C,3,...,-0.500000,-0.781831,0.623490,0,0,134,0.000000,2.966667,0.0,2.714286
2998973,2998973,2017-08-14,54,SEAFOOD,0.0,0,El Carmen,Manabi,C,3,...,-0.500000,0.000000,1.000000,0,0,133,0.000000,3.033333,0.0,3.000000
3000755,3000755,2017-08-15,54,SEAFOOD,3.0,0,El Carmen,Manabi,C,3,...,-0.500000,0.781831,0.623490,1,0,132,0.000000,2.966667,12.0,3.000000

In [10]:
sales_df.isnull().sum()

id                           0
date                         0
store_nbr                    0
family                       0
sales                        0
onpromotion                  0
city                         0
state                        0
store_type                   0
cluster                      0
dcoilwtico                   0
holiday_type                 0
is_holiday_local             0
is_holiday_regional          0
is_holiday_national          0
day_of_week                  0
month                        0
year                         0
is_weekend                   0
month_sin                    0
month_cos                    0
day_sin                      0
day_cos                      0
is_payday                    0
is_earthquake_impact         0
days_to_christmas            0
promo_ratio_vs_avg           0
store_family_velocity        1
sales_lag_7              12474
rolling_mean_7           12474
dtype: int64